# Generated by Django 5.0.2 on 2024-03-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_app', '0003_remove_poolpass_visit_limit_alter_poolpass_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poolpass',
            name='start_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата начала действия'),
        ),
    ]
