# Generated by Django 5.0.2 on 2024-03-04 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_app', '0004_alter_poolpass_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={'verbose_name': 'Инструктор', 'verbose_name_plural': 'Инструкторы'},
        ),
        migrations.AlterModelOptions(
            name='instructorreview',
            options={'verbose_name': 'Отзыв на инструктора', 'verbose_name_plural': 'Отзывы на инструкторов'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Занятие', 'verbose_name_plural': 'Занятия'},
        ),
        migrations.AlterModelOptions(
            name='poolreview',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='poolpass',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_pass', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
