# Generated by Django 5.0.2 on 2024-03-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_app', '0005_alter_instructor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='instruct_img/'),
        ),
    ]
